spring:
  profiles:
    active: local
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:healthgood1!}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDBMS_URI:localhost}:3306/health?useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${RDBMS_USERNAME:root}
    password: ${RDBMS_PASSWORD:1234}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

jwt:
  access-token:
    secret-key: ${ACCESS_SECRET_KEY:qwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwq}
    expire-millis: ${ACCESS_EXPIRE_MILLIS:10000}
  refresh-token:
    secret-key: ${REFRESH_SECRET_KEY:asasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasa}
    expire-millis: ${REFRESH_EXPIRE_MILLIS:10000000}
