spring:
  profiles:
    active: local
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:healthgood1!}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDBMS_URI:localhost}:3306/health?useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${RDBMS_USERNAME:root}
    password: ${RDBMS_PASSWORD:1234}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY:accessKey}
    secret-key: ${AWS_S3_SECRET_KEY:secretKey}

jwt:
  access-token:
    secret-key: ${ACCESS_SECRET_KEY:qwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwq}
    expire-millis: ${ACCESS_EXPIRE_MILLIS:1000000}
  refresh-token:
    secret-key: ${REFRESH_SECRET_KEY:asasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasaasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasaasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasa}
    expire-millis: ${REFRESH_EXPIRE_MILLIS:100000000}

cloud-front:
  domain: ${CLOUD_FRONT_DOMAIN_NAME:cloudFront}