spring:
  profiles:
    active:
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:healthgood1!}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDBMS_URI:localhost}:3306/health?useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${RDBMS_USERNAME:root}
    password: ${RDBMS_PASSWORD:1234}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:wy9295@gmail.com}
    password: ${GMAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}

management:
  endpoints:
    web:
      exposure:
        # 지금은 개발단계 모두 노출
        include: all

# custom env
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}

jwt:
  access-token:
    secret-key: ${ACCESS_SECRET_KEY}
    expire-millis: ${ACCESS_EXPIRE_MILLIS}
  refresh-token:
    secret-key: ${REFRESH_SECRET_KEY}
    expire-millis: ${REFRESH_EXPIRE_MILLIS}

cloud-front:
  domain: ${CLOUD_FRONT_DOMAIN_NAME}