spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    username: wy9295@gmail.com
    password: ${GMAIL_PASSWORD:password}
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID:project}
          location: asia-northeast3

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:bucketName}
    access-key: ${AWS_S3_ACCESS_KEY:accessKey}
    secret-key: ${AWS_S3_SECRET_KEY:secretKey}

cloud-front:
  domain: https://d3vt348duxk7vk.cloudfront.net

jwt:
  access-token:
    secret-key: qwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwq}
    expire-millis: 100000000000
  refresh-token:
    secret-key: asasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasaasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasaasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasa
    expire-millis: 1000000000000000