@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Ext(usr1, "User WebBrowser", "Web", "user1")
Container_Ext(usr2, "User WebBrowser", "Web", "user2")


ContainerDb(db, "Database", "NoSQL", "post persistence")
ContainerDb(redis, "Redis", "Redis", "Session Storge for Session Clustering")

Container_Boundary(server, "Notion Application Server") {
    Component(app1, "Socket Server", "WebSocket Server", "Session Management")
    Component(app2, "Socket Server", "WebSocket Server", "Session Management")
    Component(ch, "Channel Gateway", "Health Check")
    Component(post, "Post Server", "Post Server")
}

Rel(usr1, app1, "WebSocket")
Rel(app1, usr1, "WebSocket")
Rel(usr2, app2, "WebSocket")
Rel(app2, usr2, "WebSocket")
Rel(app1, redis, "Save Session and Pub/Sub")
Rel(app2, redis, "Save Session and Pub/Sub")
Rel(ch, app1, "health check")
Rel(ch, app2, "health check")
Rel(server, db, "update post and notification post")

@enduml