@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Ext(usr1, "Client", "App", "user1")
Container_Ext(gemini, "Gemini", "LLM", "")

ContainerDb(db, "Relational DB", "MySQL", "post persistence")
ContainerDb(redis, "VectorDB", "Redis", "RedisVectorStore")

Container_Boundary(server, "PocketFit Server") {
    Component(app1, "API Module", "API Server", "")
    Component(app2, "Spring AI Module", "Vertex AI Gemini", "LLM Model Handling and Embedding VectorDatabase")
    Component(ch, "Bucket4j filter", "RateLimiter")
    Component(pt, "Pt", "UseCase")
}

Rel(app1, app2, "Request Prompt       (user query)")
Rel(app2, redis, "retrieve")
Rel(usr1, app1, "pt request")
Rel(ch, app1, "user request interceptor")
Rel(ch, usr1, "Too Many Request (429)")
Rel(app2, gemini, "Generate Chat Response")
Rel(app2, pt, "Chat Response")
Rel(pt, db, "insert pt entity")

@enduml
